name: Delete GitHub Packages
on:
  workflow_dispatch: {}

jobs:
  remove:
    name: Delete all github packages
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Retrieve Package IDs
        id: retrieve-ids
        run: |
          TOKEN=${{ secrets.GIT_PACKAGE_TOKEN }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/packages"
          PACKAGE_IDS=$(curl -s -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL" | jq -r '.[] | .html_url' | awk -F/ '{print $NF}')
          echo "::set-output name=package_ids::$PACKAGE_IDS"

      - name: Delete Packages
        run: |
          TOKEN=${{ secrets.GIT_PACKAGE_TOKEN }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          PACKAGE_IDS="${{ steps.retrieve-ids.outputs.package_ids }}"
          for PACKAGE_ID in $PACKAGE_IDS; do
            curl -X DELETE -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/packages/versions/$PACKAGE_ID"
          done