name: Delete GitHub Packages
on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Latest Versions to Keep'
        required: true
        default: '5'

jobs:
  remove:
    name: Delete old github packages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/delete-package-versions@v4
          with: 
              package-name: 'xtreme-ui'
              package-type: 'npm'
              min-versions-to-keep: ${{ github.event.inputs.count }}